version: '3'
services:
  content-publisher:
    build: content-publisher
    expose:
      - 8080
      - 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
  content-subscriber:
    build: content-subscriber
    expose:
      - 8081
      - 6379
    ports:
      - 8081:8081
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"


